Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: sqssender.LambdaSender
      CodeUri: /Users/jhonatanacunahernandez/Documents/Develop/LambdaSenderSQS/HelloWorldFunction
      Runtime: java11
      Architectures:
        - x86_64